import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Footer } from "@/components/shared/footer";
import { BookOpen } from "lucide-react";

export const metadata = {
  title: "Terms of Service - StoryForge AI",
  description: "Terms of Service for StoryForge AI",
};

export default function TermsPage() {
  return (
    <div className="flex min-h-screen flex-col">
      {/* Header */}
      <header className="border-b">
        <div className="container mx-auto flex h-16 items-center justify-between px-4">
          <Link href="/" className="flex items-center gap-2">
            <BookOpen className="h-6 w-6" />
            <span className="text-xl font-bold">StoryForge AI</span>
          </Link>
          <nav className="flex items-center gap-4">
            <Link href="/login">
              <Button variant="ghost">Sign In</Button>
            </Link>
            <Link href="/signup">
              <Button>Get Started</Button>
            </Link>
          </nav>
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-1">
        <div className="container mx-auto px-4 py-16">
          <div className="mx-auto max-w-3xl prose prose-neutral dark:prose-invert">
            <h1>Terms of Service</h1>
            <p className="lead">
              Last updated: January 2026
            </p>

            <h2>1. Acceptance of Terms</h2>
            <p>
              By accessing or using StoryForge AI, you agree to be bound by these Terms of Service.
              If you do not agree to these terms, please do not use our service.
            </p>

            <h2>2. Description of Service</h2>
            <p>
              StoryForge AI is a novel writing platform that provides tools for story planning,
              character development, world-building, and AI-assisted prose generation.
            </p>

            <h2>3. User Accounts</h2>
            <p>
              To use certain features, you must create an account. You are responsible for:
            </p>
            <ul>
              <li>Maintaining the confidentiality of your account credentials</li>
              <li>All activities that occur under your account</li>
              <li>Notifying us immediately of any unauthorized use</li>
            </ul>

            <h2>4. Content Ownership</h2>
            <p>
              You retain full ownership of all content you create using StoryForge AI, including
              but not limited to stories, characters, outlines, and world-building materials.
              We claim no intellectual property rights over your creative content.
            </p>

            <h2>5. AI-Generated Content</h2>
            <p>
              Content generated by our AI features is provided as a creative tool. You are
              responsible for reviewing and editing AI-generated content. You own the rights
              to AI-generated content created through your use of the service.
            </p>

            <h2>6. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul>
              <li>Use the service for any illegal purpose</li>
              <li>Generate content that violates others&apos; rights</li>
              <li>Attempt to circumvent usage limits or security measures</li>
              <li>Share your account credentials with others</li>
              <li>Use automated systems to access the service without permission</li>
            </ul>

            <h2>7. Subscription and Payments</h2>
            <p>
              Some features require a paid subscription. By subscribing, you agree to:
            </p>
            <ul>
              <li>Pay the applicable fees as described at the time of purchase</li>
              <li>Automatic renewal unless cancelled before the renewal date</li>
              <li>Provide accurate billing information</li>
            </ul>

            <h2>8. Refunds</h2>
            <p>
              Refund requests are handled on a case-by-case basis. Contact support within
              7 days of purchase if you are unsatisfied with the service.
            </p>

            <h2>9. Service Availability</h2>
            <p>
              We strive to maintain high availability but do not guarantee uninterrupted
              service. We may modify or discontinue features with reasonable notice.
            </p>

            <h2>10. Limitation of Liability</h2>
            <p>
              StoryForge AI is provided &quot;as is&quot; without warranties of any kind. We are not
              liable for any indirect, incidental, or consequential damages arising from
              your use of the service.
            </p>

            <h2>11. Changes to Terms</h2>
            <p>
              We may update these terms from time to time. Continued use of the service
              after changes constitutes acceptance of the new terms.
            </p>

            <h2>12. Contact</h2>
            <p>
              Questions about these Terms of Service can be directed to{" "}
              <a href="mailto:legal@storyforge.ai">legal@storyforge.ai</a>.
            </p>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
